cmdargs:
    # Show style violations
    severity: style_problem

policies:
    # Disable requiring scope prefixes with variables (breaks vim-plug)
    ProhibitImplicitScopeVariable:
        enabled: false
