#!/bin/sh

output=$(acpi | tr -d ,)

battery=""
total_capacity=0
fully_charged=1
charging=0

get_value() {
    echo "$1" | cut -d " " -f "$2"
}

parse_battery() {
    battery_info=$(echo "$1" | cut -d " " -f 3-)
    status=$(get_value "$battery_info" 1)
    capacity=$(get_value "$battery_info" 2)
    time=$(get_value "$battery_info" 3 | cut -d : -f -2)

    battery="$battery$capacity"
    total_capacity=$((total_capacity + ${capacity%?}))

    if [ "$time" ]; then
        battery="$battery ($time)"
        fully_charged=0
    fi

    if [ "$status" = Charging ]; then
        charging=1
    fi
}

parse_battery "$(echo "$output" | head -1)"

second_battery="$(echo "$output" | sed --quiet 2p)"
if [ "$second_battery" ]; then
    battery="$battery + "
    parse_battery "$second_battery"
    total_capacity=$((total_capacity / 2))
fi

echo "$battery"
echo "$battery"

if [ $fully_charged = 1 ] || [ $charging = 1 ]; then
    echo "#00FF00"
elif [ $total_capacity -lt 15 ]; then
    echo "#FF0000"
elif [ $total_capacity -lt 40 ]; then
    echo "#FFFF00"
fi
