#!/bin/sh

temperature=0
total=0

# Calculate the average temperature across all thermal zones
for temp in /sys/class/thermal/thermal_zone*/temp; do
    temperature=$((temperature + $(cat "$temp")))
    total=$((total + 1))
done
temperature=$((temperature / (total * 1000)))

echo "$temperature°C"
echo "$temperature°C"

if [ "$temperature" -lt 30 ]; then
    echo "#00FF00"
elif [ "$temperature" -lt 50 ]; then
    echo "#FFFF00"
else
    echo "#FF0000"
fi
