#!/bin/sh

pacman=$(checkupdates | wc -l)
aur=$(yay -Qua | wc -l)

echo "$pacman,$aur"
echo "$pacman,$aur"

if [ "$pacman" -gt 0 ] || [ "$aur" -gt 0 ]; then
    echo "#00FF00"
else
    echo "#909090"
fi
