#!/bin/sh

output=$(acpi | tr -d , | cut -d " " -f 3-)

get_value() {
    echo "$output" | cut -d " " -f "$1"
}

status=$(get_value 1)

if [ "$status" = Full ]; then
    echo 100%
    echo 100%
    echo "#00FF00"
else
    capacity=$(get_value 2)
    time=$(get_value 3 | cut -d : -f -2)
    echo "$capacity ($time)"
    echo "$capacity ($time)"
    case $status in
        Discharging)
            integer_capacity=${capacity%?}
            if [ "$integer_capacity" -lt 15 ]; then
                echo "#FF0000"
            elif [ "$integer_capacity" -lt 40 ]; then
                echo "#FFFF00"
            fi
            ;;
        Charging)
            echo "#00FF00"
            ;;
    esac
fi
