#!/bin/sh

memory=$(free | grep Mem | awk "{ printf(\"%.1f\", \$3 / \$2 * 100) }")

echo "$memory%"
echo "$memory%"

integer_memory=$(echo "$memory" | cut -d . -f 1)

if [ "$integer_memory" -lt 25 ]; then
    echo "#00FF00"
elif [ "$integer_memory" -lt 50 ]; then
    echo "#FFFF00"
else
    echo "#FF0000"
fi
