#!/bin/bash

temperature=$(($(cat "/sys/class/thermal/$BLOCK_INSTANCE/temp") / 1000))

echo -e "$temperature°C\n"

if [ "$temperature" -lt 60 ]; then
    echo "#00FF00"
elif [ "$temperature" -lt 75 ]; then
    echo "#FFFF00"
else
    echo "#FF0000"
fi
