#!/bin/bash

temperature=0
total=0

# Calculate the average temperature across all thermal zones
for temp in /sys/class/thermal/thermal_zone*/temp; do
    ((temperature += $(cat "$temp")))
    ((total += 1))
done
((temperature /= total * 1000))

echo -e "$temperature°C\n"

if [ "$temperature" -lt 60 ]; then
    echo "#00FF00"
elif [ "$temperature" -lt 75 ]; then
    echo "#FFFF00"
else
    echo "#FF0000"
fi
