#!/bin/sh

pacman=$(checkupdates | wc -l)
cower=$(cower -u | wc -l)

echo "$pacman,$cower"
echo "$pacman,$cower"

if [ "$pacman" -gt 0 ] || [ "$cower" -gt 0 ]; then
    echo "#00FF00"
else
    echo "#909090"
fi
