#!/bin/bash

ssid=$(iwgetid -r)

if [ "$ssid" ]; then
    interface=$(tail -n 1 /proc/net/wireless | cut -d : -f 1)
    quality=$(iwconfig "$interface" | grep -oE "[0-9]+/[0-9]+" | \
        awk -F / "{ print int(\$1 / \$2 * 100) }")
    echo -e "$ssid ($quality%)\n"
    echo "#00FF00"
elif rfkill list wifi | grep -q yes; then
    echo -e "OFF\n"
    echo "#FF0000"
else
    echo -e "DOWN\n"
    echo "#FFFF00"
fi
