#!/bin/sh

ssid=$(iwgetid -r)

if [ "$ssid" ]; then
    interface=$(tail -n 1 /proc/net/wireless | cut -d : -f 1)
    quality=$(iwconfig "$interface" | grep -oE "[0-9]+/[0-9]+" | \
        awk -F / "{ print int(\$1 / \$2 * 100) }")
    echo "$ssid ($quality%)"
    echo "$ssid ($quality%)"
    echo "#00FF00"
elif rfkill list wifi | grep -q yes; then
    echo OFF
    echo OFF
    echo "#FF0000"
else
    echo DOWN
    echo DOWN
    echo "#FFFF00"
fi
